import Head from 'next/head'
import SmoothScrolling from "../components/global/SmoothScrolling"
import Cursor from '../components/global/Cursor';
import Navbar from '../components/global/Navbar';
import HeroSection from '../components/HeroSection';
import TextSeparator from '../components/TextSeparator';
import Presentation from '../components/Presentation';
import Tools from '../components/Tools';
import Works from '../components/Works';
import Reviews from '../components/Reviews';
import Footer from '../components/global/Footer';
import { SplitText } from "@cyriacbr/react-split-text";
import '../styles/globals.scss'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SmoothScrolling>
      <main>
      <Cursor />
      <Navbar />
      <HeroSection title="" description="" projects="" />
      <TextSeparator content={" Who I am - "} />
      <Presentation />
      <Tools />
      <Works />
      <Reviews />
      </main>
      <Footer />
      </SmoothScrolling>
    </>
  )
}
 